### ISSUE TITLE
Ruby version up to 2.2.0

### ISSUE THREAD

**Issue by seapy** [rossgeesman/sabjil#10]

**Comment by rossgeesman** [comment]
What is the reason? The lobsters project only supports 2.1.0. Is it because we are switching from Sphinx to full text search?

**Comment by seapy** [comment]
No, this issue no relation with full text search.

just i wish we use latest ruby version 'ㅇ'
ruby 2.2.0 many performance improve and no big compatible issue.

**Comment by rossgeesman** [comment]
Ok I will upgrade it.
